---
title: "Modelling"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(cowplot)
library(gplots)
library(ggplot2)
library(patternplot)
library(lme4)
library(visreg)
library(tidyr)
library(magrittr) 
library(dplyr)
library(ggpubr)
library(lme4)
library(lsmeans)
library(emmeans)

info<-read.csv("apoe22_33_44__2HN_3HN_4HN_mwm_combined copy.csv", header=TRUE)

reg_trials<-info %>% 
  filter(Sex != "FHet") %>% 
  filter(Stage != "Probe_D5" | Stage != "Probe_D8") %>% 
  # aesthetic purposes:
  mutate(Day = case_when( 
    Stage == "Day1" ~ 1,
    Stage == "Day2" ~ 2,
    Stage == "Day3" ~ 3,
    Stage == "Day4" ~ 4,
    Stage == "Day5" ~ 5
  )) %>% 
  filter(! is.na(Day)) %>% 
  mutate(Sex = case_when(
    Sex == "F" ~ "Female",
    Sex == "M" ~ "Male"
  )) 

probe_trials<-info %>% 
  filter(Sex != "FHet") %>% 
  filter(Stage == "Probe_D5" | Stage == "Probe_D8") %>% 
  # aesthetic purposes:
  mutate(Day = case_when( 
    Stage == "Probe_D5" ~ 1,
    Stage == "Probe_D8" ~ 2,
  )) %>% 
  filter(! is.na(Day)) %>% 
  mutate(Sex = case_when(
    Sex == "F" ~ "Female",
    Sex == "M" ~ "Male"
  )) 

# correcting for errors from Any Maze (taken from Andrei's script)
reg_trials$Distance=reg_trials$Distance/10
reg_trials$NE.distance=reg_trials$NE.distance/10
reg_trials$NW.distance=reg_trials$NW.distance/10
reg_trials$SE.distance=reg_trials$SE.distance/10
reg_trials$SW.distance=reg_trials$SW.distance/10

#Normalize time and distance in target region
reg_trials$NormSWTime<-reg_trials$SW.time/reg_trials$Duration
reg_trials$NormSWDist<-reg_trials$SW.distance/reg_trials$Distance
reg_trials<-subset(reg_trials, (NormSWTime <= 1))

reg_trials$NormSWDist <- as.numeric(reg_trials$NormSWDist)
probe_trials$NormSWDist <- as.numeric(probe_trials$NormSWDist)

hn_trials <- reg_trials %>% 
  filter(APOE == "E2HN" | APOE == "E3HN" | APOE == "E4HN") 

hn_probe <- probe_trials %>% 
  filter(APOE == "E2HN" | APOE == "E3HN" | APOE == "E4HN") 

e_trials <- reg_trials %>% 
  filter(APOE == "E22" | APOE == "E33" | APOE == "E44")

e_probe <- probe_trials %>% 
  filter(APOE == "E22" | APOE == "E33" | APOE == "E44")

e2 <- reg_trials %>% 
  filter(APOE == "E2HN" | APOE == "E22")

e2_probe <- probe_trials %>% 
  filter(APOE == "E2HN" | APOE == "E22")

e3_probe <- probe_trials %>% 
  filter(APOE == "E3HN" | APOE == "E33")

e4 <- reg_trials %>% 
  filter(APOE == "E4HN" | APOE == "E44")

e4_probe <- probe_trials %>% 
  filter(APOE == "E4HN" | APOE == "E44")
```

```{r post-hoc}
outpath='/Users/AnnaMacFarlane/Documents/mice-behavioral/mice-behavioral-plots'
data.lm<-lm(NormSWDist~APOE+Stage, reg_trials)
data.aov <- aov(data.lm)
tukey.test <- TukeyHSD(data.aov)

mytTable<-as_tibble(
  cbind(testMethod$data.name, testMethod$statistic, testMethod$p.value, testMethod$parameter[1], nrow(dfAveraged))
)

mycolnames<-c('contrast', 'statistic', 'p.value', 'df', 'observations')

postHocTable<-matrix(nrow=11, ncol=5)
postHocTable[1,]=c('', '', '', '', '')
postHocTable[2,]=c('TukeyHSD', 'mean diff', 'CIlwr', 'CIhi', 'p-value')
postHocTable[3,]=c('APOE3/3-APOE2/2', tukey.test$APOE[2,1], tukey.test$APOE[2,2], tukey.test$APOE[2,3], tukey.test$APOE[2,4])
postHocTable[4,]=c('APOE4/4-APOE2/2', tukey.test$APOE[4,1], tukey.test$APOE[4,2], tukey.test$APOE[4,3], tukey.test$APOE[4,4])
postHocTable[5,]=c('APOE4/4-APOE3/3', tukey.test$APOE[11,1], tukey.test$APOE[11,2], tukey.test$APOE[11,3], tukey.test$APOE[11,4])
postHocTable[6,]=c('E2HN-E3HN', tukey.test$APOE[7,1], tukey.test$APOE[7,2], tukey.test$APOE[7,3], tukey.test$APOE[7,4])
postHocTable[7,]=c('E4HN-E2HN', tukey.test$APOE[9,1], tukey.test$APOE[9,2], tukey.test$APOE[9,3], tukey.test$APOE[9,4])
postHocTable[8,]=c('E4HN-E3HN', tukey.test$APOE[12,1], tukey.test$APOE[12,2], tukey.test$APOE[12,3], tukey.test$APOE[12,4])
postHocTable[9,]=c('APOE2/2-E2HN', tukey.test$APOE[1,1], tukey.test$APOE[1,2], tukey.test$APOE[1,3], tukey.test$APOE[1,4])
postHocTable[10,]=c('APOE3/3-E3HN', tukey.test$APOE[10,1], tukey.test$APOE[10,2], tukey.test$APOE[10,3], tukey.test$APOE[10,4])
postHocTable[11,]=c('APOE4/4-E4HN', tukey.test$APOE[15,1], tukey.test$APOE[15,2], tukey.test$APOE[15,3], tukey.test$APOE[15,4])

myfile<-paste(outpath,'-reg-SWDist-stats.csv')
write.table(mytTable, file=myfile, col.names = mycolnames , sep = "," , row.names = F,append=TRUE)
write.table(postHocTable, file=myfile, sep=",", row.names=F, append=TRUE, col.names=F)

```

```{r lmer}

fm1<-lmer(NormSWDist ~ Stage*APOE*Sex*Diet+(1 | Animal), probe_trials)

summary(fm1)

anova(fm1)

model<-emmeans(fm1, "Sex", adjust = "Tukey")
pairs(model)
```