---
title: "MWM Analysis"
author: "Anna MacFarlane"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# installing packages 
library(tidyverse)
library(cowplot)
library(gplots)
library(ggplot2)
library(patternplot)
library(lme4)
library(visreg)
library(tidyr)
library(magrittr) 
library(dplyr)
library(ggpubr)
library(lme4)
library(lsmeans)
library(emmeans)
library(zoo)

info<-read.csv("apoe22_33_44__2HN_3HN_4HN_mwm_combined copy.csv", header=TRUE)

```

```{r organize}
# organizing data
test<-info %>% 
  filter(Sex != "FHet") %>% 
  filter(Stage != "Probe_D5" | Stage != "Probe_D8") %>% 
  # aesthetic purposes:
  mutate(Stage = case_when( 
    Stage == "Day1" ~ "Day 1",
    Stage == "Day2" ~ "Day 2",
    Stage == "Day3" ~ "Day 3",
    Stage == "Day4" ~ "Day 4",
    Stage == "Day5" ~ "Day 5"
  )) %>% 
  filter(! is.na(Stage)) %>% 
  mutate(Sex = case_when(
    Sex == "F" ~ "Female",
    Sex == "M" ~ "Male"
  )) %>% 
  group_by(Animal, Stage, add = TRUE) %>% 
  #group_by(Stage) %>% 
  summarize(
    Duration = mean(Duration),
    Distance = mean(Distance)
  )

reg_trials<-info %>% 
  filter(Sex != "FHet") %>% 
  filter(Stage != "Probe_D5" | Stage != "Probe_D8") %>% 
  # aesthetic purposes:
  mutate(Day = case_when( 
    Stage == "Day1" ~ 1,
    Stage == "Day2" ~ 2,
    Stage == "Day3" ~ 3,
    Stage == "Day4" ~ 4,
    Stage == "Day5" ~ 5
  )) %>% 
  filter(! is.na(Day)) %>% 
  mutate(Sex = case_when(
    Sex == "F" ~ "Female",
    Sex == "M" ~ "Male"
  )) 

probe_trials<-info %>% 
  filter(Sex != "FHet") %>% 
  filter(Stage == "Probe_D5" | Stage == "Probe_D8") %>% 
  # aesthetic purposes:
  mutate(Day = case_when( 
    Stage == "Probe_D5" ~ 1,
    Stage == "Probe_D8" ~ 2,
  )) %>% 
  filter(! is.na(Day)) %>% 
  mutate(Sex = case_when(
    Sex == "F" ~ "Female",
    Sex == "M" ~ "Male"
  )) 

# correcting for errors from Any Maze (taken from Andrei's script)
reg_trials$Distance=reg_trials$Distance/10
reg_trials$NE.distance=reg_trials$NE.distance/10
reg_trials$NW.distance=reg_trials$NW.distance/10
reg_trials$SE.distance=reg_trials$SE.distance/10
reg_trials$SW.distance=reg_trials$SW.distance/10

#Normalize time and distance in target region
reg_trials$NormSWTime<-reg_trials$SW.time/reg_trials$Duration
reg_trials$NormSWDist<-reg_trials$SW.distance/reg_trials$Distance
reg_trials<-subset(reg_trials, (NormSWTime <= 1))

#Normalize Probe Distances
probe_trials$DistTot<-probe_trials$NE.distance+probe_trials$NW.distance+probe_trials$SE.distance+probe_trials$SW.distance
probe_trials$NE.Dist.Norm<-probe_trials$NE.distance/probe_trials$DistTot
probe_trials$NW.Dist.Norm<-probe_trials$NW.distance/probe_trials$DistTot
probe_trials$SE.Dist.Norm<-probe_trials$SE.distance/probe_trials$DistTot
probe_trials$SW.Dist.Norm<-probe_trials$SW.distance/probe_trials$DistTot

#Normalize Probe Times
probe_trials$TimeTot<-probe_trials$NE.time+probe_trials$NW.time+probe_trials$SE.time+probe_trials$SW.time
probe_trials$NE.Time.Norm<-probe_trials$NE.time/probe_trials$TimeTot
probe_trials$NW.Time.Norm<-probe_trials$NW.time/probe_trials$TimeTot
probe_trials$SE.Time.Norm<-probe_trials$SE.time/probe_trials$TimeTot
probe_trials$SW.Time.Norm<-probe_trials$SW.time/probe_trials$TimeTot

# Converting NormSWDiet values to numeric
reg_trials$NormSWDist <- as.numeric(reg_trials$NormSWDist)
probe_trials$NormSWDist <- as.numeric(probe_trials$NormSWDist)

# Individual datasets for regular trials 
hn_trials <- reg_trials %>% 
  filter(APOE == "E2HN" | APOE == "E3HN" | APOE == "E4HN") 
e_trials <- reg_trials %>% 
  filter(APOE == "E22" | APOE == "E33" | APOE == "E44")
e2 <- reg_trials %>% 
  filter(APOE == "E2HN" | APOE == "E22")
e3 <- reg_trials %>% 
  filter(APOE == "E3HN" | APOE == "E33")
e4 <- reg_trials %>% 
  filter(APOE == "E4HN" | APOE == "E44")

# Individual datasets for probe trials
hn_probe <- probe_trials %>% 
  filter(APOE == "E2HN" | APOE == "E3HN" | APOE == "E4HN") 
e_probe <- probe_trials %>% 
  filter(APOE == "E22" | APOE == "E33" | APOE == "E44")
e2_probe <- probe_trials %>% 
  filter(APOE == "E2HN" | APOE == "E22")
e3_probe <- probe_trials %>% 
  filter(APOE == "E3HN" | APOE == "E33")
e4_probe <- probe_trials %>% 
  filter(APOE == "E4HN" | APOE == "E44")

```

```{r post-hoc}

fm1<-lmer(NormSWDist ~ Stage*APOE*Sex*Diet+(1 | Animal), probe_trials)
a1<-anova(fm1)

a1

lm1<-lm(NormSWDist ~ Sex + factor(APOE), probe_trials)
model<-emmeans(lm1, "Sex", adjust = "Tukey")
pairs(model)

summary(fm1)
confint(fm1)

a1<-anova(fm1)

model<-emmeans(fm1, "Sex", adjust = "Tukey")
pairs(model)

model<-emmeans(fm1, "APOE", adjust = "Tukey")
pairs(model)



```


lm <- lm(Duration ~ Sex*APOE*Diet, reg_trials)
summary(lm)
anova(lm)

```{r reg-norm-sw-dist}
ggline(reg_trials, x='Stage', y='NormSWDist',
       color='APOE', fill='APOE', facet.by=c('Diet','Sex'), 
       error.plot='errorbar', add='mean_se',
       palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, legend='top')

ggline(hn_trials, x='Stage', y='NormSWDist',
       color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, legend='top')

ggline(e_trials, x='Stage', y='NormSWDist', 
       color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5,  legend='top')

ggline(e2, x='Stage', y='NormSWDist', 
       color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5,  legend='top')

ggline(e3, x='Stage', y='NormSWDist', 
       color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5,  legend='top')

ggline(e4, x='Stage', y='NormSWDist', 
       color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5,  legend='top')
```

```{r probe-norm-sw-dist}
ggline(probe_trials, x='Stage', y='NormSWDist',
       color='APOE', fill='APOE', facet.by=c('Diet','Sex'), 
       error.plot='errorbar', add='mean_se',
       palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, legend='top')

ggline(hn_probe, x='Stage', y='NormSWDist',
       color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, legend='top')

ggline(e_probe, x='Stage', y='NormSWDist', 
       color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5,  legend='top')

ggline(e2_probe, x='Stage', y='NormSWDist', 
       color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5,  legend='top')

ggline(e3_probe, x='Stage', y='NormSWDist', 
       color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5,  legend='top')

ggline(e4_probe, x='Stage', y='NormSWDist', 
       color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5,  legend='top')
```

```{r violin}
day5<- probe_trials %>% 
  filter(Stage == "Probe_D5")

day8<-probe_trials %>% 
  filter(Stage == "Probe_D8")

ggplot(day5, aes(Diet, NormSWDist, fill = Sex)) +
  geom_violin(alpha = 0.5) +
  facet_grid(. ~ APOE)  +
  #geom_boxplot(width = 0.1, outlier.color = "red") +
  geom_jitter(size = 0.5, height = 0, width = 0.3, aes(color = Sex)) + 
  labs(title = "Probe Trial: Day 5")

ggplot(day8, aes(Diet, NormSWDist, fill = Sex)) +
  geom_violin(alpha = 0.5) +
  facet_grid(. ~ APOE)  +
  #geom_boxplot(width = 0.1, outlier.color = "red") +
  geom_jitter(size = 0.5, height = 0, width = 0.3, aes(color = Sex)) +
  labs(title = "Probe Trial: Day 8")
```

```{r probe-dist}
ggline(probe_trials, x='Stage', y='Distance', color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, legend='top')

ggline(hn_probe, x='Stage', y='Distance', color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, legend='top')

ggline(e_probe, x='Stage', y='Distance', color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, legend='top')

ggline(e2_probe, x='Stage', y='Distance', color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, legend='top')

ggline(e3_probe, x='Stage', y='Distance', color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, legend='top')

ggline(e4_probe, x='Stage', y='Distance', color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, legend='top')
```

```{r reg-duration, message = FALSE}
ggline(reg_trials, x='Stage', y='Duration', color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, xlab='', ylab='Time to Platform (s)', legend='top')

ggline(hn_trials, x='Stage', y='Duration', color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, xlab='', ylab='Time to Platform (s)', legend='top')

ggline(e_trials, x='Stage', y='Duration', color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, xlab='', ylab='Time to Platform (s)', legend='top')

ggline(e2, x='Stage', y='Duration', color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, xlab='', ylab='Time to Platform (s)', legend='top')

ggline(e3, x='Stage', y='Duration', color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, xlab='', ylab='Time to Platform (s)', legend='top')

ggline(e4, x='Stage', y='Duration', color='APOE', fill='APOE', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', palette = c('blueviolet', 'chartreuse1', 'red','pink','gray','blue', 'orange'), size=1,
       point.size=1.5, xlab='', ylab='Time to Platform (s)', legend='top')
```
       
```{r duration, message = FALSE}

plot1<-ggplot(reg_trials, aes(Day, Duration, 
                 color = APOE, fill = APOE)) +
  geom_jitter(size = .5, alpha = 0.25) +
  geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  theme_bw() +
  labs(title = "MWM Duration - all genotypes",
       subtitle = "Males and females")

plot2<-ggplot(reg_trials, aes(Day, Duration, 
                 color = APOE, fill = APOE)) +
  geom_jitter(size = .5, alpha = 0.25) +
  geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  facet_grid(. ~ Sex) +
  theme_bw()  +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 

plot1<-ggplot(hn_trials, aes(Day, Duration, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
  geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  theme_bw() +
  labs(title = "MWM Duration - HN genotypes",
       subtitle = "Males and females")

plot2<-ggplot(hn_trials, aes(Day, Duration, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  facet_grid(. ~ Sex) +
  theme_bw()  +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 

plot1<-ggplot(e_trials, aes(Day, Duration, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  theme_bw() +
  labs(title = "MWM Duration - non-HN genotypes",
       subtitle = "Males and females")

plot2<-ggplot(e_trials, aes(Day, Duration, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  facet_grid(. ~ Sex) +
  theme_bw()  +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 
```


```{r sw-distance, message = FALSE}
plot1<-ggplot(reg_trials, aes(Day, SW.distance, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  theme_bw() +
  labs(title = "SW Distance - all genotypes",
       subtitle = "Males and females")

plot2<-ggplot(reg_trials, aes(Day, SW.distance, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  facet_grid(. ~ Sex) +
  theme_bw()  +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 

plot1<-ggplot(hn_trials, aes(Day, SW.distance, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  theme_bw() +
  labs(title = "SW Distance - HN genotypes",
       subtitle = "Males and females")

plot2<-ggplot(hn_trials, aes(Day, SW.distance, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  facet_grid(. ~ Sex) +
  theme_bw()  +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 

plot1<-ggplot(e_trials, aes(Day, SW.distance, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  theme_bw() +
  labs(title = "SW Distance - non-HN genotypes",
       subtitle = "Males and females")

plot2<-ggplot(e_trials, aes(Day, SW.distance, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  facet_grid(. ~ Sex) +
  theme_bw()  +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 
```

```{r norm-sw-distance, message = FALSE}
plot1<-ggplot(reg_trials, aes(Day, NormSWDist, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  theme_bw() +
  labs(title = "Normalized SW Distance - all genotypes",
       subtitle = "Males and females")

plot2<-ggplot(reg_trials, aes(Day, NormSWDist, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  facet_grid(. ~ Sex) +
  theme_bw()  +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 

plot1<-ggplot(hn_trials, aes(Day, NormSWDist, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  theme_bw() +
  labs(title = "Normalized SW Distance - HN genotypes",
       subtitle = "Males and females")

plot2<-ggplot(hn_trials, aes(Day, NormSWDist, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  facet_grid(. ~ Sex) +
  theme_bw()  +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 

plot1<-ggplot(e_trials, aes(Day, NormSWDist, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  theme_bw() +
  labs(title = "Normalized SW Distance - non-HN genotypes",
       subtitle = "Males and females")

plot2<-ggplot(e_trials, aes(Day, NormSWDist, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  facet_grid(. ~ Sex) +
  theme_bw()  +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 
```

```{r sw-time, message = FALSE}
plot1<-ggplot(reg_trials, aes(Day, SW.time, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  theme_bw() +
  labs(title = "SW Time - all genotypes",
       subtitle = "Males and females")

plot2<-ggplot(reg_trials, aes(Day, SW.time, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  facet_grid(. ~ Sex) +
  theme_bw()  +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 

plot1<-ggplot(hn_trials, aes(Day, SW.time, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  theme_bw() +
  labs(title = "SW Time - HN genotypes",
       subtitle = "Males and females")

plot2<-ggplot(hn_trials, aes(Day, SW.time, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  facet_grid(. ~ Sex) +
  theme_bw()  +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 

plot1<-ggplot(e_trials, aes(Day, SW.time, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  theme_bw() +
  labs(title = "SW Time - non-HN genotypes",
       subtitle = "Males and females")

plot2<-ggplot(e_trials, aes(Day, SW.time, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  facet_grid(. ~ Sex) +
  theme_bw()  +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 
```


```{r norm-sw-time, message = FALSE}
plot1<-ggplot(reg_trials, aes(Day, NormSWTime, 
                 color = APOE, fill = APOE)) +
  geom_jitter(size = .5, alpha = 0.25) +
  geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  theme_bw() +
  labs(title = "Normalized SW Time - all genotypes",
       subtitle = "Males and females") 

plot2<-ggplot(reg_trials, aes(Day, NormSWTime, 
                 color = APOE, fill = APOE)) +
  geom_jitter(size = .5, alpha = 0.25) +
  geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  facet_grid(. ~ Sex) +
  theme_bw()  +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 

plot1<-ggplot(hn_trials, aes(Day, NormSWTime, 
                 color = APOE, fill = APOE)) +
  geom_jitter(size = .5, alpha = 0.25) +
  geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  theme_bw() +
  labs(title = "Normalized SW Time - HN genotypes",
       subtitle = "Males and females")

plot2<-ggplot(hn_trials, aes(Day, NormSWTime, 
                 color = APOE, fill = APOE)) +
  geom_jitter(size = .5, alpha = 0.25) +
  geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  facet_grid(. ~ Sex) +
  theme_bw()  +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 

plot1<-ggplot(e_trials, aes(Day, NormSWTime, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  theme_bw() +
  labs(title = "Normalized SW Time - non-HN genotypes",
       subtitle = "Males and females")

plot2<-ggplot(e_trials, aes(Day, NormSWTime, 
                 color = APOE, fill = APOE)) +
   geom_jitter(size = .5, alpha = 0.25) +
   geom_line(aes(y=rollmean(NormSWTime, 7, na.pad=TRUE))) +
  facet_grid(. ~ Sex) +
  theme_bw()  +
  theme(legend.position="none")

ggdraw() + 
  draw_plot(plot1, 0, .5, 1, .5) +
  draw_plot(plot2, 0, 0, 1, .5) 
```