---
title: "WN"
output: html_notebook
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(cowplot)
library(gplots)
library(ggplot2)
library(patternplot)
library(lme4)
library(visreg)
library(tidyr)
library(magrittr) 
library(dplyr)
library(ggpubr)
library(lme4)
library(lsmeans)
library(emmeans)
library(rstatix)

```

```{r data}
# uploading all of the MWM data, including AWN and other trial data
mwm_data<-read.csv('MWM_combined_data.csv', header=TRUE)

# uploading mice age information
mice_info<-read.csv('qial_animals_with_age.csv')

# merging with qial information 
index = match(  mwm_data$AnimalID , mice_info$BadeaID)
sum(mice_info$BadeaID [index] != mwm_data$AnimalID)
#index = na.omit(index)
mwm_data= cbind(mice_info[ index,],  mwm_data)


# exported this file to add the Age_Handling in Excel, then reuploaded it
#write.csv(mwm_data, '/Users/AnnaMacFarlane/Desktop/MWM_AWN_Combined.csv')

mwm_data$Age_Handling = as.numeric(mwm_data$Age_Handling)
# setting age groups
mwm_data<-mwm_data %>% 
  mutate(Age_group = case_when(
    Age_Handling < 7 ~ '6 Months',
    #Age_Handling >= 7 & Age_Handling <= 14 ~ 'Young',
    Age_Handling > 14 ~ 'Old',
    TRUE ~ 'Young'
  ))



# NO NEED TO RUN THIS
mwm_data<-read.csv('mwm_data_refined.csv')

data1<-read.csv('Winding/210614MWM_positions.csv', header=TRUE)
data2<-read.csv('Winding/220207MWM_positions.csv', header=TRUE)
data3<-read.csv('Winding/220606MWM_positions.csv', header=TRUE)
data4<-read.csv('Winding/190715MWM_positions.csv', header=TRUE)
data5<-read.csv('Winding/210503MWM_positions.csv', header=TRUE)
data6<-read.csv('Winding/200302MWM_positions.csv', header=TRUE)
data7<-read.csv('Winding/211004MWM_positions.csv', header=TRUE)
data8<-read.csv('Winding/210811MWM_positions.csv', header=TRUE)
data9<-read.csv('Winding/190919MWM_positions.csv', header=TRUE)
data10<-read.csv('Winding/220509MWM_positions.csv', header=TRUE)
data11<-read.csv('Winding/220110MWM_positions.csv', header=TRUE)
data12<-read.csv('Winding/220307MWM_positions.csv', header=TRUE)
data13<-read.csv('Winding/220404MWM_positions.csv', header=TRUE)
data14<-read.csv('Winding/190617MWM_positions.csv', header=TRUE)
data14$Row = gsub ( "061019", "190610", data14$Row)
data15<-read.csv('Winding/210118MWM_positions.csv', header=TRUE)
data16<-read.csv('Winding/201016MWM_positions.csv', header=TRUE)
data17<-read.csv('Winding/200331MWM_positions.csv', header=TRUE)
data18<-read.csv('Winding/211122MWM_positions.csv', header=TRUE)
data19<-read.csv('Winding/210906MWM_positions.csv', header=TRUE)
data20<-read.csv('Winding/221128MWM_positions.csv', header=TRUE)
data21<-read.csv('Winding/220808MWM_positions.csv', header=TRUE)
data22<-read.csv('Winding/220422MWM_positions.csv', header=TRUE)
data23<-read.csv('Winding/210222MWM_positions.csv', header=TRUE)
data24<-read.csv('Winding/210906MWM_positions.csv', header=TRUE)
data25<-read.csv('Winding/221101MWM_positions.csv', header=TRUE)
data26<-read.csv('Winding/221003MWM_positions.csv', header=TRUE)
data27<-read.csv('Winding/220905MWM_positions.csv', header=TRUE)
data28<-read.csv('Winding/220704MWM_positions.csv', header=TRUE)
data29<-read.csv('Winding/210201MWM_positions.csv', header=TRUE)


data_joan<-read.csv('Winding/JoanMWM_positions.csv', header=TRUE)
```

```{r merge-data}

# NO NEED TO RUN ANY OF THIS
wn<-rbind(data1,data2,data3,data4,data5,data6,data7,data8,data9,data10,data11,
          data12,data13,data14,data15,data16,data17,data18,data19, data20, data21,
          data22, data23, data24, data25, data26, data27, data28, data29)

# creating column with cohort ID and stage and time
wn['CohortID']=as.integer(substr(wn$Row, 1, 6))
wn$AnimalID=substr(wn$Row, 1, 9)

index_temp = substr(wn$AnimalID,9,9) == "_"
wn$AnimalID[index_temp] = substr(wn$AnimalID[index_temp],1,8)
wn$AnimalID = gsub("-" , "_", wn$AnimalID)


n_last_time <- 15                                # Specify number of characters to extract
wn$Time=as.integer(substr(wn$Row, nchar(wn$Row)-n_last_time+1, nchar(wn$Row)-n_last_time+1))

n_last_stage <- 21
wn$Stage<-substr(wn$Row, nchar(wn$Row) - n_last_stage + 1, nchar(wn$Row)-n_last_stage+4)

#index_probe = grep("e", wn$AnimalID)
wn$Stage = gsub('e', 'Probe', wn$Stage)

#write.csv(wn, '/Users/AnnaMacFarlane/Desktop/CombinedAWN.csv')

# reading in other MWM data 

#mwm_data<-read.csv('mwm_data.csv', header=TRUE)
#mwm_data<-subset(mwm_data, select=-c(X, age))

# merging data 
mwm_data <- left_join(wn, mwm_data, by = c("AnimalID" = "Animal", "Time"="Trial", 'Stage'='Stage')) %>%
 distinct(Row, .keep_all =TRUE)

# calculating normalized distances in each quadrant

mwm_data$Distance=mwm_data$Distance/10
mwm_data$NE___distance=mwm_data$NE___distance/10
mwm_data$NW___distance=mwm_data$NW___distance/10
mwm_data$SE___distance=mwm_data$SE___distance/10
mwm_data$SW___distance=mwm_data$SW___distance/10

#Normalize time and distance in target region
mwm_data$NormSWTime<-mwm_data$SW___time/mwm_data$Duration
mwm_data$NormSWDist<-mwm_data$SW___distance/mwm_data$Distance
mwm_data<-subset(mwm_data, (NormSWTime <= 1))

#Normalize Probe Distances
mwm_data$DistTot<-mwm_data$NE___distance+mwm_data$NW___distance+mwm_data$SE___distance+mwm_data$SW___distance
mwm_data$NE.Dist.Norm<-mwm_data$NE___distance/mwm_data$DistTot
mwm_data$NW.Dist.Norm<-mwm_data$NW___distance/mwm_data$DistTot
mwm_data$SE.Dist.Norm<-mwm_data$SE___distance/mwm_data$DistTot
mwm_data$SW.Dist.Norm<-mwm_data$SW___distance/mwm_data$DistTot

#Normalize Probe Times
mwm_data$TimeTot<-mwm_data$NE___time+mwm_data$NW___time+mwm_data$SE___time+mwm_data$SW___time
mwm_data$NE.Time.Norm<-mwm_data$NE___time/mwm_data$TimeTot
mwm_data$NW.Time.Norm<-mwm_data$NW___time/mwm_data$TimeTot
mwm_data$SE.Time.Norm<-mwm_data$SE___time/mwm_data$TimeTot
mwm_data$SW.Time.Norm<-mwm_data$SW___time/mwm_data$TimeTot

#Normalize time and distance in target region probe
mwm_data$NormSWTime<-mwm_data$SW___time/mwm_data$Duration
mwm_data$NormSWDist<-mwm_data$SW___distance/mwm_data$Distance
mwm_data<-subset(mwm_data, (NormSWTime <= 1))

# Converting NormSWDiet values to numeric
mwm_data$NormSWDist <- as.numeric(mwm_data$NormSWDist)
mwm_data$NormSWDist <- as.numeric(mwm_data$NormSWDist)

mwm_data$NewM<-mwm_data$NormSWDist/(mwm_data$Winding_numbers+1)


#write.csv(allMWM, '/Users/AnnaMacFarlane/Desktop/AllMWM_Combined.csv')


# merging with additional animal information
#index = match(  mice_info$BadeaID, mwm_data$AnimalID )
#sum(mice_info$BadeaID [index] != mwm_data$AnimalID)
#index = na.omit(index)
#temp= cbind(mwm_data[ index,],  mice_info)

# overwriting the merged data because this has updated ages at handling
#mwm_data<-read.csv('MWM_AWN_Combined 3.csv', header=TRUE)


```

```{r joan}
joan<-read.csv('joan_wn.csv', header=TRUE)
joan_ref<-read.csv('JOAN_MWM_combined.csv', header=TRUE)

joan_wn_all<-left_join(joan, joan_ref, by = c("CohortID" = "Animal_ID"))

joan_wn<-joan_wn_all %>% 
  filter(!is.na(X)) %>% 
  filter(Stage != "Probe_D5" | Stage != "Probe_D8") %>%
  mutate(Stage = case_when( 
    Stage == "Day1" ~ "Day 1",
    Stage == "Day2" ~ "Day 2",
    Stage == "Day3" ~ "Day 3",
    Stage == "Day4" ~ "Day 4",
    Stage == "Day5" ~ "Day 5"
  )) %>% 
  filter(!is.na(Stage)) %>% 
  group_by(Stage)
  

ggline(joan_wn, x='Stage', y='Winding_numbers',
       #facet.by=c('Sex'),
       error.plot='errorbar', add='mean_se', size=1,
       point.size=1.5, legend='top')

ggline(joan_wn, x='Stage', y='Winding_numbers',
       error.plot='errorbar', add='mean_se')
```

```{r organize}


# setting age groups
mwm_data<-mwm_data %>% 
  mutate(Age_group = case_when(
    Age_Months <= 16 ~ 'Young',
    Age_Months > 16 ~ 'Old'
  ))

hn_trials <- mwm_data %>% 
  filter(Genotype == "APOE22HN" | Genotype == "APOE33HN" | Genotype == "APOE44HN") %>% 
  filter(Stage != 'Probe_D5' & Stage != 'Probe_D8') %>% 
  #filter(!is.na(Genotype)) %>% 
  mutate(Coll_Geno = case_when(
    Genotype == 'APOE22' ~ '22 + 22HN',
    Genotype == 'APOE22HN' ~ '22 + 22HN',
    Genotype == 'APOE33' ~ '33 + 33HN',
    Genotype == 'APOE33HN' ~ '33 + 33HN',
    Genotype == 'APOE44' ~ '44 + 44HN',
    Genotype == 'APOE44HN' ~ '44 + 44HN'
  )) %>% 
  filter(!is.na(Age_group))
  
hn_trials_ctrl<- hn_trials %>% 
  filter(Diet_x=='Control')

hn_trials_hfd<-hn_trials %>% 
  filter(Diet_x=='HFD')
  
probe_hn<-mwm_data %>% 
  filter(Genotype == "APOE22HN" | Genotype == "APOE33HN" | Genotype == "APOE44HN") %>% 
  filter(Stage == 'Probe_D5' | Stage == 'Probe_D8') %>% 
  filter(!is.na(Age_group))

e_trials <- mwm_data %>% 
  filter(Genotype == "APOE22" | Genotype == "APOE33" | Genotype == "APOE44") %>% 
  filter(Stage != 'Probe_D5' & Stage != 'Probe_D8') %>% 
  filter(!is.na(Age_group)) 
  
e_trials_ctrl <- e_trials%>% 
  filter(Diet_x=='Control')

e_trials_hfd <- e_trials %>% 
  filter(Diet_x=='HFD')
  
probe_e<-mwm_data %>% 
  filter(Genotype == "APOE22" | Genotype == "APOE33" | Genotype == "APOE44") %>% 
  filter(Stage == 'Probe_D5' | Stage == 'Probe_D8')  %>% 
  filter(!is.na(Age_group))

probe_all<-mwm_data %>% 
  filter(Stage == 'Probe_D5' | Stage == 'Probe_D8')  %>% 
  filter(!is.na(Age_group)) %>% 
  mutate(Coll_Geno = case_when(
    Genotype == 'APOE22' ~ '22 + 22HN',
    Genotype == 'APOE22HN' ~ '22 + 22HN',
    Genotype == 'APOE33' ~ '33 + 33HN',
    Genotype == 'APOE33HN' ~ '33 + 33HN',
    Genotype == 'APOE44' ~ '44 + 44HN',
    Genotype == 'APOE44HN' ~ '44 + 44HN'
  ))
  
#e2 <- mwm_wn %>% 
#  filter(Geno == "APOE22HN" | Geno == "APOE22")
#e3 <- mwm_wn %>% 
#  filter(Geno == "APOE33HN" | Geno == "APOE33")
#e4 <- mwm_wn %>% 
#  filter(Geno == "APOE44HN" | Geno == "APOE44")
  
all<-mwm_data %>% 
  filter(Stage != 'Probe_D5' & Stage != 'Probe_D8') %>% 
  filter(!is.na(Genotype)) %>% 
  mutate(Coll_Geno = case_when(
    Genotype == 'APOE22' ~ '22 + 22HN',
    Genotype == 'APOE22HN' ~ '22 + 22HN',
    Genotype == 'APOE33' ~ '33 + 33HN',
    Genotype == 'APOE33HN' ~ '33 + 33HN',
    Genotype == 'APOE44' ~ '44 + 44HN',
    Genotype == 'APOE44HN' ~ '44 + 44HN'
  )) %>% 
  filter(!is.na(Coll_Geno)) %>% 
  filter(!is.na(Age_group))

```



```{r plots}
ggline(hn_trials, x='Stage', y='Winding_numbers',
       color='Geno', fill='Geno', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c("#6a0dad", "#008000", "#FF0000"), size=1,
       point.size=1.5, legend='top')
       
# facet by age and sex
par(mfrow=c(1,1))
jpeg("basic_ctrl_facetAgeSex_AWN.jpeg", units="in", width=7, height=5, res=300)  

ggline(e_trials_ctrl, x='Stage', y='Winding_numbers', 
       color='Genotype', fill='Genotype', facet.by=c('Age_group','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c("#1BCC97", "#1B50CC", "#CC1BA8"), size=1,
       point.size=1.5,  legend='top', title = 'Winding Number')
      
dev.off()
       
ggline(e_trials, x='Stage', y='Distance', 
       color='Genotype', fill='Genotype', facet.by=c('Age_group','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c("#1BCC97", "#1B50CC", "#CC1BA8"), size=1,
       point.size=1.5,  legend='top')       

ggline(e_trials, x='Stage', y='NormSWDist', 
       color='Genotype', fill='Genotype', facet.by=c('Age_group','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c("#1BCC97", "#1B50CC", "#CC1BA8"), size=1,
       point.size=1.5,  legend='top')
       
# Just genotype, no facet  

all<-all %>% 
  mutate(Line_type = case_when(
    Genotype=='APOE22' ~ 'Basic',
    Genotype=='APOE22HN' ~ 'HN',
    Genotype=='APOE33' ~ 'Basic',
    Genotype=='APOE33HN' ~ 'HN',
    Genotype=='APOE44' ~ 'Basic',
    Genotype=='APOE44HN' ~ 'HN'
))

# single factor plots: updated color, fill, and stat_compare_means group to change
# what factor is being expressed

# Diet basic lines
par(mfrow=c(1,1))
jpeg("basic_NSW_diet_full.jpeg", units="in", width=7, height=5, res=300) 
ggline(e_trials, x='Stage', y='NormSWDist', 
       color='Diet_x', fill='Diet_x',
       error.plot='errorbar', add='mean_se', facet.by=c('Genotype'),
       palette = c('blue', 'orange'), size=1,
       point.size=1.5,  legend='top', title='Normalized SW Dist') +
       stat_compare_means(aes(group = Diet_x), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")
dev.off()
 
par(mfrow=c(1,1))
jpeg("basic_AWN_diet_full.jpeg", units="in", width=7, height=5, res=300)       
ggline(e_trials, x='Stage', y='Winding_numbers', 
       color='Diet_x', fill='Diet_x',
       error.plot='errorbar', add='mean_se',  facet.by=c('Genotype'),
       palette = c('blue', 'orange'),size=1,
       point.size=1.5,  legend='top', title='Winding Number') +
       stat_compare_means(aes(group = Diet_x), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left") 
dev.off()

par(mfrow=c(1,1))
jpeg("basic_Dist_diet_full.jpeg", units="in", width=7, height=5, res=300)        
ggline(e_trials, x='Stage', y='Distance', 
       color='Diet_x', fill='Diet_x',
       error.plot='errorbar', add='mean_se', size=1,  facet.by=c('Genotype'),
       palette = c('blue', 'orange'),
       point.size=1.5,  legend='top', title='Total Distance')  +
       stat_compare_means(aes(group = Diet_x), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")     
dev.off()

# Diet HN lines
par(mfrow=c(1,1))
jpeg("hn_NSW_diet_full.jpeg", units="in", width=7, height=5, res=300) 
ggline(hn_trials, x='Stage', y='NormSWDist', 
       color='Diet_x', fill='Diet_x',
       error.plot='errorbar', add='mean_se',  facet.by=c('Genotype'),
       palette = c('blue', 'orange'), size=1,
       point.size=1.5,  legend='top', title='Normalized SW Dist') +
       stat_compare_means(aes(group = Diet_x), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")
dev.off()
 
par(mfrow=c(1,1))
jpeg("hn_AWN_diet_full.jpeg", units="in", width=7, height=5, res=300)       
ggline(hn_trials, x='Stage', y='Winding_numbers', 
       color='Diet_x', fill='Diet_x',
       error.plot='errorbar', add='mean_se',  facet.by=c('Genotype'),
       palette = c('blue', 'orange'),size=1,
       point.size=1.5,  legend='top', title='Winding Number') +
       stat_compare_means(aes(group = Diet_x), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left") 
dev.off()

par(mfrow=c(1,1))
jpeg("hn_Dist_diet_full.jpeg", units="in", width=7, height=5, res=300)        
ggline(hn_trials, x='Stage', y='Distance', 
       color='Diet_x', fill='Diet_x',  facet.by=c('Genotype'),
       error.plot='errorbar', add='mean_se', size=1,
       palette = c('blue', 'orange'),
       point.size=1.5,  legend='top', title='Total Distance')  +
       stat_compare_means(aes(group = Diet_x), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")     
dev.off()

# Diet collapsed genotypes
par(mfrow=c(1,1))
jpeg("all_NSW_diet_full.jpeg", units="in", width=7, height=5, res=300) 
ggline(all, x='Stage', y='NormSWDist', 
       color='Diet_x', fill='Diet_x',
       error.plot='errorbar', add='mean_se',  facet.by=c('Coll_Geno'),
       palette = c('blue', 'orange'), size=1,
       point.size=1.5,  legend='top', title='Normalized SW Dist') +
       stat_compare_means(aes(group = Diet_x), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")
dev.off()
 
par(mfrow=c(1,1))
jpeg("all_AWN_diet_full.jpeg", units="in", width=7, height=5, res=300)       
ggline(all, x='Stage', y='Winding_numbers', 
       color='Diet_x', fill='Diet_x',  facet.by=c('Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c('blue', 'orange'),size=1,
       point.size=1.5,  legend='top', title='Winding Number') +
       stat_compare_means(aes(group = Diet_x), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left") 
dev.off()

par(mfrow=c(1,1))
jpeg("all_Dist_diet_full.jpeg", units="in", width=7, height=5, res=300)        
ggline(all, x='Stage', y='Distance', 
       color='Diet_x', fill='Diet_x',  facet.by=c('Coll_Geno'),
       error.plot='errorbar', add='mean_se', size=1,
       palette = c('blue', 'orange'),
       point.size=1.5,  legend='top', title='Total Distance')  +
       stat_compare_means(aes(group = Diet_x), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")     
dev.off()
       
       
       
       

ggline(e2, x='Stage', y='Winding_numbers', 
       color='Geno', fill='Geno', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', 
      palette = c("#1BCC97", "#6a0dad"), size=1,
       point.size=1.5,  legend='top')

ggline(e3, x='Stage', y='Winding_numbers', 
       color='Geno', fill='Geno', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c("#1B50CC", "#008000"), size=1,
       point.size=1.5,  legend='top')

ggline(e4, x='Stage', y='Winding_numbers', 
       color='Geno', fill='Geno', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c("#CC1BA8", "#FF0000"), size=1,
       point.size=1.5,  legend='top')
```

```{r facet-by-sex}
ggline(e_trials, x='Stage', y='Winding_numbers', 
       color='Sex', fill='Sex', facet.by=c('Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex') 
       
# facet by age and genotype
ggline(e_trials_ctrl, x='Stage', y='Winding_numbers', 
       color='Sex', fill='Sex', facet.by=c('Age_group','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex') +
       stat_compare_means(aes(group = Sex), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")
       
animal_counts<-distinct(mwm_data, Age_Substracted, .keep_all = TRUE)
table(mwm_data[mwm_data$Age_Substracted])
       
ggline(e_trials_ctrl, x='Stage', y='Distance', 
       color='Sex', fill='Sex', facet.by=c('Age_group','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex') +
       stat_compare_means(aes(group = Sex), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")
       
ggline(e_trials_ctrl, x='Stage', y='NormSWDist', 
       color='Sex', fill='Sex', facet.by=c('Age_group','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex') +
       stat_compare_means(aes(group = Sex), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")

ggline(e_trials, x='Stage', y='NewM', 
       color='Sex', fill='Sex', facet.by=c('Age_group','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex')       
       
# facet by sex and genotype 

par(mfrow=c(1,1))
jpeg("basic_AWN_age_full.jpeg", units="in", width=7, height=5, res=300) 
ggline(e_trials, x='Stage', y='Winding_numbers', 
       color='Age_group', fill='Age_group', facet.by=c('Sex','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("purple", "green"), size=1,
       point.size=1.5,  legend='top', legend.title='Age Group', title='Winding Number') +
       stat_compare_means(aes(group = Age_group), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")
dev.off()
      
par(mfrow=c(1,1))
jpeg("basic_NSW_age_full.jpeg", units="in", width=7, height=5, res=300)        
ggline(e_trials, x='Stage', y='NormSWDist', 
       color='Age_group', fill='Age_group', facet.by=c('Sex','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("purple", "green"), size=1,
       point.size=1.5,  legend='top', legend.title='Age Group', 
       title='Normalized SW Distance') +
       stat_compare_means(aes(group = Age_group), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")
dev.off()

par(mfrow=c(1,1))
jpeg("basic_Dist_age_full.jpeg", units="in", width=7, height=5, res=300) 
ggline(e_trials, x='Stage', y='Distance', 
       color='Age_group', fill='Age_group', facet.by=c('Sex','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("purple", "green"), size=1,
       point.size=1.5,  legend='top', legend.title='Age Group', 
       title='Total Distance') +
       stat_compare_means(aes(group = Age_group), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")
dev.off()
       

# basic lines collapse age 

par(mfrow=c(1,1))
jpeg("basic_AWN_sex_full.jpeg", units="in", width=7, height=5, res=300)
ggline(e_trials, x='Stage', y='Winding_numbers', 
       color='Sex', fill='Sex', facet.by=c('Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex', title='Winding Number') +
       stat_compare_means(aes(group = Sex), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")
dev.off()

par(mfrow=c(1,1))
jpeg("basic_dist_sex_full.jpeg", units="in", width=7, height=5, res=300)
ggline(e_trials, x='Stage', y='Distance', 
       color='Sex', fill='Sex', facet.by=c('Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex', title='Total Distance') +
       stat_compare_means(aes(group = Sex), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")
dev.off()
  
par(mfrow=c(1,1))
jpeg("basic_NSW_sex_full.jpeg", units="in", width=7, height=5, res=300)     
ggline(e_trials, x='Stage', y='NormSWDist', 
       color='Sex', fill='Sex', facet.by=c('Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex', title='Normalized SW Dist') +
       stat_compare_means(aes(group = Sex), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")  
dev.off()
       
# geno and age with diet lines within basic lines

ggline(e_trials, x='Stage', y='Winding_numbers', 
       color='Diet_x', fill='Diet_x', facet.by=c('Age_group', 'Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("blue", "orange"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex', title='Winding Number') +
       stat_compare_means(aes(group = Diet_x), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")

ggline(e_trials, x='Stage', y='Distance', 
       color='Diet_x', fill='Diet_x', facet.by=c('Age_group', 'Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("blue", "orange"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex', title='Total Distance') +
       stat_compare_means(aes(group = Diet_x), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")
       
ggline(e_trials, x='Stage', y='NormSWDist', 
       color='Diet_x', fill='Diet_x', facet.by=c('Age_group', 'Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("blue", "orange"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Diet_x', title='Normalized SW Dist') +
       stat_compare_means(aes(group = Diet_x), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")  
 
# basic lines collapse sex

par(mfrow=c(1,1))
jpeg("hn_AWN_age_full.jpeg", units="in", width=7, height=5, res=300)
ggline(hn_trials, x='Stage', y='Winding_numbers', 
       color='Age_group', fill='Age_group', facet.by=c('Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("purple", "green"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Age Group', title='Winding Number') +
       stat_compare_means(aes(group = Age_group), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")  
dev.off()

par(mfrow=c(1,1))
jpeg("hn_dist_age_full.jpeg", units="in", width=7, height=5, res=300)
ggline(hn_trials, x='Stage', y='Distance', 
       color='Age_group', fill='Age_group', facet.by=c('Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("purple", "green"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Age Group', title='Total Distance') +
       stat_compare_means(aes(group = Age_group), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left") 
dev.off()

par(mfrow=c(1,1))
jpeg("hn_NSW_age_full.jpeg", units="in", width=7, height=5, res=300)
ggline(hn_trials, x='Stage', y='NormSWDist', 
       color='Age_group', fill='Age_group', facet.by=c('Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("purple", "green"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Age Group', title='Normalized SW Dist') +
       stat_compare_means(aes(group = Age_group), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")
dev.off()


par(mfrow=c(1,1))
jpeg("all_NSW_age_full.jpeg", units="in", width=7, height=5, res=300)
ggline(all, x='Stage', y='NormSWDist', 
       color='Age_group', fill='Age_group', facet.by=c('Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("purple", "green"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Age Group', title='Normalized SW Dist') +
       stat_compare_means(aes(group = Age_group), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")
dev.off()

par(mfrow=c(1,1))
jpeg("all_AWN_age_full.jpeg", units="in", width=7, height=5, res=300)
ggline(all, x='Stage', y='Winding_numbers', 
       color='Age_group', fill='Age_group', facet.by=c('Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("purple", "green"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Age Group') +
       stat_compare_means(aes(group = Age_group), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")
dev.off()

par(mfrow=c(1,1))
jpeg("all_dist_age_full.jpeg", units="in", width=7, height=5, res=300)
ggline(all, x='Stage', y='Distance', 
       color='Age_group', fill='Age_group', facet.by=c('Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("purple", "green"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Age Group') +
       stat_compare_means(aes(group = Age_group), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")
dev.off()

       
 
# facet by age group, colored by genotype 

ggline(e_trials, x='Stage', y='Winding_numbers', 
       color='Genotype', fill='Genotype', facet.by=c('Age_group'),
       error.plot='errorbar', add='mean_se', 
       #palette = c("purple", "green"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Genotype', title='Winding Number')        
       
       
#animal_counts<-distinct(e_trials, AnimalID, .keep_all = TRUE)
#table(animal_counts[animal_counts$Genotype == 'APOE33', ]$Age_group)
```

```{r new-m-plots}
ggline(e_trials, x='Stage', y='NewM', 
       color='Genotype', fill='Genotype', facet.by=c('Diet','Sex'),
       error.plot='errorbar', add='mean_se', 
       palette = c("#1BCC97", "#1B50CC", "#CC1BA8"), size=1,
       point.size=1.5,  legend='top', legend.title='Sex')
       
       
stat.test <- e_trials_ctrl %>%
  group_by(Genotype) %>%
  #t_test(Winding_numbers ~ Sex) %>%
  nest() %>% 
mutate(
ttest=map(e_trials_ctrl,~ t_test(Winding_numbers ~ Sex, paired=F,data = .x))) %>%
      adjust_pvalue(method = "bonferroni") %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj")
stat.test
stat.test <- stat.test %>% add_xy_position(x = "Stage")


ggline(e_trials_ctrl, x='Stage', y='Winding_numbers', 
       color='Sex', fill='Sex', facet.by=c('Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex') + 
       stat_compare_means(aes(group = Sex), label = "p.signif")
       
       #stat.test,  label = "p.adj.signif", tip.length = 0.01)
       
       
       #stat_compare_means(method='anova', aes(group=Sex)) +
       #stat_compare_means(aes(label = after_stat(p.signif)),
                  #method = "t.test", ref.group = ".all.")
       #stat_compare_means(aes(group = Sex), label = "p.signif", 
                     #label.y = c(16, 25, 29))
       
ggline(e_trials, x='Stage', y='NewM', 
       color='Sex', fill='Sex', facet.by=c('Age_group','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex')
       
ggline(e_trials, x='Stage', y='NewM', 
       color='Age_group', fill='Age_group', facet.by=c('Sex','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("green", "purple"), size=1,
       point.size=1.5,  legend='top', legend.title='Sex')

```

```{r all-geno}
ggline(all, x='Stage', y='Winding_numbers', 
       color='Sex', fill='Sex', facet.by=c('Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex')
       
ggline(all, x='Stage', y='Distance', 
       color='Sex', fill='Sex', facet.by=c('Age_group','Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex')
       
ggline(all, x='Stage', y='NewM', 
       color='Age_group', fill='Age_group', facet.by=c('Sex','Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("green", "purple"), size=1,
       point.size=1.5,  legend='top', legend.title='Sex')
       
ggline(all, x='Stage', y='NormSWDist', 
       color='Age_group', fill='Age_group', facet.by=c('Sex','Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("green", "purple"), size=1,
       point.size=1.5,  legend='top', legend.title='Sex')
       
       
# Collapsed genotype and sex
ggline(all, x='Stage', y='Winding_numbers', 
       color='Coll_Geno', fill='Coll_Geno',
       error.plot='errorbar', add='mean_se', size=1,
       point.size=1.5,  legend='top',
       legend.title='Genotype') 

ggline(all, x='Stage', y='Distance', 
       color='Coll_Geno', fill='Coll_Geno',
       error.plot='errorbar', add='mean_se', size=1,
       point.size=1.5,  legend='top',
       legend.title='Genotype') 

ggline(all, x='Stage', y='NewM', 
       color='Coll_Geno', fill='Coll_Geno',
       error.plot='errorbar', add='mean_se', size=1,
       point.size=1.5,  legend='top',
       legend.title='Genotype') 
       
ggline(all, x='Stage', y='NormSWDist', 
       color='Coll_Geno', fill='Coll_Geno',
       error.plot='errorbar', add='mean_se', size=1,
       point.size=1.5,  legend='top',
       legend.title='Genotype') 
       
# Sex collapsed, combined HN and regular lines

ggline(all, x='Stage', y='Winding_numbers', 
       color='Sex', fill='Sex', facet.by=c('Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex') 
       
ggline(all, x='Stage', y='NewM', 
       color='Sex', fill='Sex', facet.by=c('Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex') 
       
ggline(all, x='Stage', y='Distance', 
       color='Sex', fill='Sex', facet.by=c('Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex') 
       
ggline(all, x='Stage', y='NormSWDist', 
       color='Sex', fill='Sex', facet.by=c('Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex') 

# Age collapsed, combined HN and regular lines 
ggline(all, x='Stage', y='Winding_numbers', 
       color='Age_group', fill='Age_group', facet.by=c('Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("green", "purple"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Age Group') 
       
ggline(all, x='Stage', y='NewM', 
       color='Age_group', fill='Age_group', facet.by=c('Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("green", "purple"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Age Group') 
       
ggline(all, x='Stage', y='Distance', 
       color='Age_group', fill='Age_group', facet.by=c('Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("green", "purple"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Age Group') 
       
ggline(all, x='Stage', y='NormSWDist', 
       color='Age_group', fill='Age_group', facet.by=c('Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("green", "purple"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Age Group') 
       
# Combined lines faceted by age and colored sex
ggline(all, x='Stage', y='Winding_numbers', 
       color='Sex', fill='Sex', facet.by=c('Age_group','Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex')
       
ggline(all, x='Stage', y='NewM', 
       color='Sex', fill='Sex', facet.by=c('Age_group','Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex')
       
ggline(all, x='Stage', y='Distance', 
       color='Sex', fill='Sex', facet.by=c('Age_group','Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex')
       
ggline(all, x='Stage', y='NormSWDist', 
       color='Sex', fill='Sex', facet.by=c('Age_group','Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex')
       
# Combined lines faceted by sex and colored age
ggline(all, x='Stage', y='Winding_numbers', 
       color='Age_group', fill='Age_group', facet.by=c('Sex','Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("green", "purple"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Age Group')
       
ggline(all, x='Stage', y='NewM', 
       color='Age_group', fill='Age_group', facet.by=c('Sex','Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("green", "purple"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Age Group')

ggline(all, x='Stage', y='Distance', 
       color='Age_group', fill='Age_group', facet.by=c('Sex','Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("green", "purple"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Age Group')

ggline(all, x='Stage', y='NormSWDist', 
       color='Age_group', fill='Age_group', facet.by=c('Sex','Coll_Geno'),
       error.plot='errorbar', add='mean_se', 
       palette = c("green", "purple"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Age Group')
       

ggline(all, x='Stage', y='NewM', 
       color='Coll_Geno', fill='Coll_Geno',
       error.plot='errorbar', add='mean_se', 
       palette = c("green", "purple", 'blue'), size=1,
       point.size=1.5,  legend='top')
       
       
ggplot(data=all, aes(x=Stage, y=Winding_numbers, color=Age_group)) +
  geom_line(stat="identity", width=0.5) +
  facet_grid(Sex~Coll_Geno) + 
  #labs(y="Average Percent Freezing Time", x='Component') +
  #geom_errorbar(aes(ymin=len-se, ymax=len+se), width=0.2, size=0.5)+
  theme_bw()  
  #labs(title="Learning Curve", x="Time", 
  #     y='Mean Percent Time Freezing', 
  #     legend='Genotype') +
  #scale_x_continuous(breaks=c(1, 2, 3)) +
  #scale_color_manual(values = c("#6a0dad", "#1BCC97"))
```

```{r hn-line}

# HN lines faceted by sex and genotype, lines age

ggline(hn_trials, x='Stage', y='Winding_numbers', 
       color='Sex', fill='Sex', facet.by=c('Age_group','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex')
       
ggline(hn_trials, x='Stage', y='Distance', 
       color='Sex', fill='Sex', facet.by=c('Age_group','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex')

ggline(hn_trials, x='Stage', y='NormSWDist', 
       color='Sex', fill='Sex', facet.by=c('Age_group','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex')      

ggline(hn_trials, x='Stage', y='NewM', 
       color='Sex', fill='Sex', facet.by=c('Age_group','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("red", "blue"), size=1,
       point.size=1.5,  legend='top',
       legend.title='Sex')

# HN lines faceted by sex and genotype, lines age group
       
ggline(hn_trials, x='Stage', y='NewM', 
       color='Age_group', fill='Age_group', facet.by=c('Sex','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("green", "purple"), size=1,
       point.size=1.5,  legend='top', legend.title='Sex')
       
ggline(hn_trials, x='Stage', y='NormSWDist', 
       color='Age_group', fill='Age_group', facet.by=c('Sex','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("purple", "green"), size=1,
       point.size=1.5,  legend='top', legend.title='Sex')
       
ggline(hn_trials, x='Stage', y='Winding_numbers', 
       color='Age_group', fill='Age_group', facet.by=c('Sex','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("purple", "green"), size=1,
       point.size=1.5,  legend='top', legend.title='Sex')

ggline(hn_trials, x='Stage', y='Distance', 
       color='Age_group', fill='Age_group', facet.by=c('Sex','Genotype'),
       error.plot='errorbar', add='mean_se', 
       palette = c("purple", "green"), size=1,
       point.size=1.5,  legend='top', legend.title='Sex')
       
```

par(mfrow=c(1,1))
jpeg("day0_basic_facetGeno_sex.jpeg", units="in", width=7, height=5, res=300)  

ggline(day0_basic_sex, x='Time', y='Pct.Total.Time.Freezing',
       color='Sex', fill='Sex', facet.by=c('Genotype'), 
       error.plot='errorbar', add='mean_se',
       palette = c("red", "blue"), size=1,
       point.size=1.5, legend='top', title='Learning Curve') +
       stat_compare_means(aes(group = Sex), label = "p.signif", hide.ns=TRUE,
       label.y.npc = "bottom", label.x.npc = "left")

dev.off()

```{r probe-plots}

par(mfrow=c(1,1))
jpeg("basic_probe_NSW_geno_stat.jpeg", units="in", width=7, height=5, res=300) 

ggplot(data = probe_e, aes(factor(Stage), NormSWDist)) +
  geom_violin() + geom_boxplot(width = 0.1) +
  theme_bw()+ facet_grid(.~Genotype) + 
  geom_jitter(height = 0, width = 0.3, size = 0.7, aes(color = Genotype)) +
  #labs(y = "Mean Percent Freezing Time", x='') +
  scale_color_manual(values = c("#1BCC97", "#1B50CC", "#CC1BA8")) +
  labs(title='Normalized SW Dist') +
  stat_compare_means(aes(group = Genotype), label = "p.signif", hide.ns=TRUE,
  label.y.npc = "bottom", label.x.npc = "left")

dev.off()
  

par(mfrow=c(1,1))
jpeg("basic_probe_AWN_geno_stat.jpeg", units="in", width=7, height=5, res=300) 

ggplot(data = probe_e, aes(factor(Stage), Winding_numbers)) +
  geom_violin() + geom_boxplot(width = 0.1) +
  theme_bw()+ facet_grid(.~Genotype) + 
  geom_jitter(height = 0, width = 0.3, size = 0.7, aes(color = Genotype)) +
  labs(title='Winding Number') +
  scale_color_manual(values = c("#1BCC97", "#1B50CC", "#CC1BA8"))  +
  stat_compare_means(aes(group = Genotype), label = "p.signif", hide.ns=TRUE,
  label.y.npc = "bottom", label.x.npc = "left")
dev.off()  

par(mfrow=c(1,1))
jpeg("basic_probe_dist_geno_stat.jpeg", units="in", width=7, height=5, res=300)
ggplot(data = probe_e, aes(factor(Stage), Distance)) +
  geom_violin() + geom_boxplot(width = 0.1) +
  theme_bw()+ facet_grid(.~Genotype) + 
  geom_jitter(height = 0, width = 0.3, size = 0.7, aes(color = Genotype)) +
  labs(title ='Total Distance') +
  scale_color_manual(values = c("#1BCC97", "#1B50CC", "#CC1BA8")) +
  stat_compare_means(aes(group = Genotype), label = "p.signif", hide.ns=TRUE,
  label.y.npc = "bottom", label.x.npc = "left")
dev.off()


# probe HN lines 
par(mfrow=c(1,1))
jpeg("hn_probe_AWN_geno_stat.jpeg", units="in", width=7, height=5, res=300) 
ggplot(data = probe_hn, aes(factor(Stage), Winding_numbers)) +
  geom_violin() + geom_boxplot(width = 0.1) +
  theme_bw()+ facet_grid(.~Genotype) + 
  geom_jitter(height = 0, width = 0.3, size = 0.7, aes(color = Genotype)) +
  labs(title='Winding Number') +
  scale_color_manual(values = c("#6a0dad", "#008000", "#FF0000"))  +
  stat_compare_means(aes(group = Genotype), label = "p.signif", hide.ns=TRUE,
  label.y.npc = "bottom", label.x.npc = "left")
dev.off()  

par(mfrow=c(1,1))
jpeg("hn_probe_NSW_geno_stat.jpeg", units="in", width=7, height=5, res=300)
ggplot(data = probe_hn, aes(factor(Stage), NormSWDist)) +
  geom_violin() + geom_boxplot(width = 0.1) +
  theme_bw()+ facet_grid(.~Genotype) + 
  geom_jitter(height = 0, width = 0.3, size = 0.7, aes(color = Genotype)) +
  labs(title ='Normalized SW Dist') +
  scale_color_manual(values = c("#6a0dad", "#008000", "#FF0000")) +
  stat_compare_means(aes(group = Genotype), label = "p.signif", hide.ns=TRUE,
  label.y.npc = "bottom", label.x.npc = "left")
dev.off()

# probe collapsed genotype

probe_all<-probe_all %>% 
  filter(!is.na(Coll_Geno))

par(mfrow=c(1,1))
jpeg("all_probe_AWN_geno_stat.jpeg", units="in", width=7, height=5, res=300) 
ggplot(data = probe_all, aes(factor(Stage), Winding_numbers)) +
  geom_violin() + geom_boxplot(width = 0.1) +
  theme_bw()+ facet_grid(.~Coll_Geno) + 
  geom_jitter(height = 0, width = 0.3, size = 0.7, aes(color = Coll_Geno)) +
  labs(title='Winding Number') +
  stat_compare_means(aes(group = Genotype), label = "p.signif", hide.ns=TRUE,
  label.y.npc = "bottom", label.x.npc = "left")
dev.off()  

par(mfrow=c(1,1))
jpeg("all_probe_NSW_geno_stat.jpeg", units="in", width=7, height=5, res=300)
ggplot(data = probe_all, aes(factor(Stage), NormSWDist)) +
  geom_violin() + geom_boxplot(width = 0.1) +
  theme_bw()+ facet_grid(.~Coll_Geno) + 
  geom_jitter(height = 0, width = 0.3, size = 0.7, aes(color = Coll_Geno)) +
  labs(title ='Normalized SW Dist') +
  stat_compare_means(aes(group = Genotype), label = "p.signif", hide.ns=TRUE,
  label.y.npc = "bottom", label.x.npc = "left")
dev.off()





# faceted by stage and age as factor
ggplot(data = probe_e, aes(factor(Age_group), Distance)) +
  geom_violin() + geom_boxplot(width = 0.1) +
  theme_bw()+ facet_grid(Stage~Genotype) + 
  geom_jitter(height = 0, width = 0.3, size = 0.7, aes(color = Genotype)) +
  #labs(y = "Mean Percent Freezing Time", x='') +
  scale_color_manual(values = c("#1BCC97", "#1B50CC", "#CC1BA8"))   

ggplot(data = probe_e, aes(factor(Age_group), Winding_numbers)) +
  geom_violin() + geom_boxplot(width = 0.1) +
  theme_bw()+ facet_grid(Stage~Genotype) + 
  geom_jitter(height = 0, width = 0.3, size = 0.7, aes(color = Genotype)) +
  #labs(y = "Mean Percent Freezing Time", x='') +
  scale_color_manual(values = c("#1BCC97", "#1B50CC", "#CC1BA8"))  
 
ggplot(data = probe_e, aes(factor(Age_group), NormSWDist)) +
  geom_violin() + geom_boxplot(width = 0.1) +
  theme_bw()+ facet_grid(Stage~Genotype) + 
  geom_jitter(height = 0, width = 0.3, size = 0.7, aes(color = Genotype)) +
  #labs(y = "Mean Percent Freezing Time", x='') +
  scale_color_manual(values = c("#1BCC97", "#1B50CC", "#CC1BA8"))   
  
  
  

  
```


```{r post-hoc-reg}
library(lmerTest)
# try bootstrapping
all<-all %>% 
  mutate(line_factor = case_when(
    Genotype == 'APOE22' ~ 0,
    Genotype == 'APOE22HN' ~ 1,
    Genotype == 'APOE33' ~ 0,
    Genotype == 'APOE33HN' ~ 1,
    Genotype == 'APOE44' ~ 0,
    Genotype == 'APOE44HN' ~ 1
))


# AWN basic lines
emm_options(pbkrtest.limit = 7000)

mod_1_awn_basic<-lmer(Winding_numbers~factor(Genotype)*Sex*Age_group+Stage+(1|AnimalID), e_trials_ctrl)
mix_1_wn<-emmeans(mod_1_awn_basic, "Sex", adjust = "Tukey")
pairs(mix_1_wn)
mix_1_wn_geno<-emmeans(mod_1_awn_basic, "Genotype", adjust = "Tukey")
pairs(mix_1_wn_geno)
mix_1_wn_age<-emmeans(mod_1_awn_basic, "Age_group", adjust = "Tukey")
pairs(mix_1_wn_age)
a1_a<-anova(mod_1_awn_basic)
a1_a

# AWN basic lines full model
mod_1_awn_basic<-lmer(Winding_numbers~factor(Genotype)*Sex*Age_group+Stage+Diet_x+(1|AnimalID), e_trials)
mix_1_wn<-emmeans(mod_1_awn_basic, "Sex", adjust = "Tukey")
pairs(mix_1_wn)
mix_1_wn_geno<-emmeans(mod_1_awn_basic, "Genotype", adjust = "Tukey")
pairs(mix_1_wn_geno)
mix_1_wn_age<-emmeans(mod_1_awn_basic, "Age_group", adjust = "Tukey")
pairs(mix_1_wn_age)
mix_1_wn_age<-emmeans(mod_1_awn_basic, "Diet_x", adjust = "Tukey")
pairs(mix_1_wn_age)
a1_a<-anova(mod_1_awn_basic)
a1_a

# AWN HN lines full model
mod_1_awn_hn<-lmer(Winding_numbers~factor(Genotype)*Sex*Age_group+Stage+Diet_x+(1|AnimalID), hn_trials)
mix_1_wn<-emmeans(mod_1_awn_hn, "Sex", adjust = "Tukey")
pairs(mix_1_wn)
mix_1_wn_geno<-emmeans(mod_1_awn_hn, "Genotype", adjust = "Tukey")
pairs(mix_1_wn_geno)
mix_1_wn_age<-emmeans(mod_1_awn_hn, "Age_group", adjust = "Tukey")
pairs(mix_1_wn_age)
mix_1_wn_age<-emmeans(mod_1_awn_hn, "Diet_x", adjust = "Tukey")
pairs(mix_1_wn_age)
a1_a<-anova(mod_1_awn_hn)
a1_a

# AWN full model
mod_1_wn<-lmer(Winding_numbers~factor(Coll_Geno)*Sex*Age_group+Stage+line_factor+Diet_x+(1|AnimalID), all)
mix_1_wn_sex<-emmeans(mod_1_wn, "Sex", adjust = "Tukey")
pairs(mix_1_wn_sex)
mix_1_wn_CollGeno<-emmeans(mod_1_wn, "Coll_Geno", adjust = "Tukey")
pairs(mix_1_wn_CollGeno)
mix_1_wn_Age<-emmeans(mod_1_wn, "Age_group", adjust = "Tukey")
pairs(mix_1_wn_Age)
mix_1_wn_Line<-emmeans(mod_1_wn, "line_factor", adjust = "Tukey")
pairs(mix_1_wn_Line)
mix_1_wn_Diet<-emmeans(mod_1_wn, "Diet_x", adjust = "Tukey")
pairs(mix_1_wn_Diet)
a1<-anova(mod_1_wn)
a1

# AWN hn lines
mod_1_wn_hn<-lmer(Winding_numbers~factor(Genotype)*Sex*Age_group+Stage+(1|AnimalID), hn_trials_ctrl)
mix_1_wn_sex_hn<-emmeans(mod_1_wn_hn, "Sex", adjust = "Tukey")
pairs(mix_1_wn_sex_hn)
mix_1_wn_Genotype_hn<-emmeans(mod_1_wn_hn, "Genotype", adjust = "Tukey")
pairs(mix_1_wn_Genotype_hn)
mix_1_wn_Age_hn<-emmeans(mod_1_wn_hn, "Age_group", adjust = "Tukey")
pairs(mix_1_wn_Age_hn)
a1_hn<-anova(mod_1_wn_hn)
a1_hn

# Total distance full model
mod_1_dist<-lmer(Distance~factor(Coll_Geno)*Sex*Age_group+Stage+Diet_x+line_factor+(1|AnimalID), all)
mix_1_dist<-emmeans(mod_1_dist, "Sex", adjust = "Tukey")
pairs(mix_1_dist)
mix_1_dist_CollGeno<-emmeans(mod_1_dist, "Coll_Geno", adjust = "Tukey")
pairs(mix_1_dist_CollGeno)
mix_1_dist_Age<-emmeans(mod_1_dist, "Age_group", adjust = "Tukey")
pairs(mix_1_dist_Age)
mix_1_dist_line<-emmeans(mod_1_dist, "line_factor", adjust = "Tukey")
pairs(mix_1_dist_line)
mix_1_dist_diet<-emmeans(mod_1_dist, "Diet_x", adjust = "Tukey")
pairs(mix_1_dist_diet)
a2<-anova(mod_1_dist)
a2

# Total Distance basic lines
mod_1_dist_basic <-lmer(Distance~factor(Genotype)*Sex*Age_group+Stage+Diet_x+(1|AnimalID), e_trials)
mix_1_dist_basic <-emmeans(mod_1_dist_basic, "Sex", adjust = "Tukey")
pairs(mix_1_dist_basic)
mix_1_dist_basic_Geno<-emmeans(mod_1_dist_basic, "Genotype", adjust = "Tukey")
pairs(mix_1_dist_basic_Geno)
mix_1_dist_Age<-emmeans(mod_1_dist_basic, "Age_group", adjust = "Tukey")
pairs(mix_1_dist_Age)
mix_1_dist_Diet<-emmeans(mod_1_dist_basic, "Diet_x", adjust = "Tukey")
pairs(mix_1_dist_Diet)
a2_dist_basic<-anova(mod_1_dist_basic)
a2_dist_basic

# Total Distance HN lines
mod_1_dist_hn <-lmer(Distance~factor(Genotype)*Sex*Age_group+Stage+Diet_x+(1|AnimalID), hn_trials)
mix_1_dist_hn <-emmeans(mod_1_dist_hn, "Sex", adjust = "Tukey")
pairs(mix_1_dist_hn)
mix_1_dist_hn_Geno<-emmeans(mod_1_dist_hn, "Genotype", adjust = "Tukey")
pairs(mix_1_dist_hn_Geno)
mix_1_dist_Age<-emmeans(mod_1_dist_hn, "Age_group", adjust = "Tukey")
pairs(mix_1_dist_Age)
mix_1_dist_Diet<-emmeans(mod_1_dist_hn, "Diet_x", adjust = "Tukey")
pairs(mix_1_dist_Diet)
a2_dist_hn<-anova(mod_1_dist_hn)
a2_dist_hn



# Norm SW Distance full model
mod_1_normSW<-lmer(NormSWDist~factor(Coll_Geno)*Sex*Age_group+Stage+line_factor+Diet_x+(1|AnimalID), all)
mix_1_normSW_Age<-emmeans(mod_1_normSW, "Age_group", adjust = "Tukey")
pairs(mix_1_normSW_Age)
mix_1_normSW_CollGeno<-emmeans(mod_1_normSW, "Coll_Geno", adjust = "Tukey")
pairs(mix_1_normSW_CollGeno)
mix_1_normSW_Sex<-emmeans(mod_1_normSW, "Sex", adjust = "Tukey")
pairs(mix_1_normSW_Sex)
mix_1_normSW_line<-emmeans(mod_1_normSW, "line_factor", adjust = "Tukey")
pairs(mix_1_normSW_line)
mix_1_normSW_diet<-emmeans(mod_1_normSW, "Diet_x", adjust = "Tukey")
pairs(mix_1_normSW_diet)
a4<-anova(mod_1_normSW)
a4

# NSW basic full model
mod_1_normSW_basic<-lmer(NormSWDist~factor(Genotype)*Sex*Age_group+Stage+Diet_x+(1|AnimalID), e_trials)
mix_1_normSW_Age<-emmeans(mod_1_normSW_basic, "Age_group", adjust = "Tukey")
pairs(mix_1_normSW_Age)
mix_1_normSW_Geno<-emmeans(mod_1_normSW_basic, "Genotype", adjust = "Tukey")
pairs(mix_1_normSW_Geno)
mix_1_normSW_Sex<-emmeans(mod_1_normSW_basic, "Sex", adjust = "Tukey")
pairs(mix_1_normSW_Sex)
mix_1_normSW_diet<-emmeans(mod_1_normSW_basic, "Diet_x", adjust = "Tukey")
pairs(mix_1_normSW_diet)
a4<-anova(mod_1_normSW_basic)
a4


# NSW HN full model
mod_1_normSW_hn<-lmer(NormSWDist~factor(Genotype)*Sex*Age_group+Stage+Diet_x+(1|AnimalID), hn_trials)
mix_1_normSW_Age<-emmeans(mod_1_normSW_hn, "Age_group", adjust = "Tukey")
pairs(mix_1_normSW_Age)
mix_1_normSW_Geno<-emmeans(mod_1_normSW_hn, "Genotype", adjust = "Tukey")
pairs(mix_1_normSW_Geno)
mix_1_normSW_Sex<-emmeans(mod_1_normSW_hn, "Sex", adjust = "Tukey")
pairs(mix_1_normSW_Sex)
mix_1_normSW_diet<-emmeans(mod_1_normSW_hn, "Diet_x", adjust = "Tukey")
pairs(mix_1_normSW_diet)
a4<-anova(mod_1_normSW_hn)
a4


# within day 5 and within day 8

basic_day5<-probe_e %>% 
  filter(Stage=='Probe_D5')

basic_day8<-probe_e %>% 
  filter(Stage=='Probe_D8')

hn_day5<-probe_hn%>% 
  filter(Stage=='Probe_D5')

hn_day8<-probe_hn%>% 
  filter(Stage=='Probe_D8')

pooled_day5<-probe_all%>% 
  filter(Stage=='Probe_D5')

pooled_day8<-probe_all %>% 
  filter(Stage=='Probe_D8')

library(lme4)

lm_pre<-lm(Pct.Total.Time.Freezing~Treatment+factor(Coll_Geno)*Sex*Age_group+Treatment, pretone)

mod_probe_d5_basic_NSW<-lm(NormSWDist~factor(Genotype)*Sex*Age_group+Diet_x, basic_day5)
mod_probe_d5_hn_NSW<-lm(NormSWDist~factor(Genotype)*Sex*Age_group+Diet_x, hn_day5)
mod_probe_d5_pooled_NSW<-lm(NormSWDist~factor(Coll_Geno)*Sex*Age_group+Diet_x, pooled_day5)

mod_probe_d5_basic_AWN<-lm(Winding_numbers~factor(Genotype)*Sex*Age_group*Diet_x, basic_day5)
mod_probe_d5_hn_AWN<-lm(Winding_numbers~factor(Genotype)*Sex*Age_group*Diet_x, hn_day5)
mod_probe_d5_pooled_AWN<-lm(Winding_numbers~factor(Coll_Geno)*Sex*Age_group*Diet_x, pooled_day5)

mod_probe_d8_basic_NSW<-lm(NormSWDist~factor(Genotype)*Sex*Age_group+Diet_x, basic_day8)
mod_probe_d8_hn_NSW<-lm(NormSWDist~factor(Genotype)*Sex*Age_group+Diet_x, hn_day8)
mod_probe_d8_pooled_NSW<-lm(NormSWDist~factor(Coll_Geno)*Sex*Age_group+Diet_x, pooled_day8)

mod_probe_d8_basic_AWN<-lm(Winding_numbers~factor(Genotype)*Sex*Age_group*Diet_x, basic_day8)
mod_probe_d8_hn_AWN<-lm(Winding_numbers~factor(Genotype)*Sex*Age_group*Diet_x, hn_day8)
mod_probe_d8_pooled_AWN<-lm(Winding_numbers~factor(Coll_Geno)*Sex*Age_group*Diet_x, pooled_day8)

mix_basic_d5_NSW<-emmeans(mod_probe_d5_basic_NSW, "Genotype", adjust = "Tukey")
mix_hn_d5_NSW<-emmeans(mod_probe_d5_hn_NSW, "Genotype", adjust = "Tukey")
mix_pooled_d5_NSW<-emmeans(mod_probe_d5_pooled_NSW, "Coll_Geno", adjust = "Tukey")

mix_basic_d5_AWN<-emmeans(mod_probe_d5_basic_AWN, "Genotype", adjust = "Tukey")
mix_hn_d5_AWN<-emmeans(mod_probe_d5_hn_AWN, "Genotype", adjust = "Tukey")
mix_pooled_d5_AWN<-emmeans(mod_probe_d5_pooled_AWN, "Coll_Geno", adjust = "Tukey")

mix_basic_d8_NSW<-emmeans(mod_probe_d8_basic_NSW, "Genotype", adjust = "Tukey")
mix_hn_d8_NSW<-emmeans(mod_probe_d8_hn_NSW, "Genotype", adjust = "Tukey")
mix_pooled_d8_NSW<-emmeans(mod_probe_d8_pooled_NSW, "Coll_Geno", adjust = "Tukey")

mix_basic_d8_AWN<-emmeans(mod_probe_d8_basic_AWN, "Genotype", adjust = "Tukey")
mix_hn_d8_AWN<-emmeans(mod_probe_d8_hn_AWN, "Genotype", adjust = "Tukey")
mix_pooled_d8_AWN<-emmeans(mod_probe_d8_pooled_AWN, "Coll_Geno", adjust = "Tukey")

pairs(mix_basic_d5_NSW)
pairs(mix_hn_d5_NSW)
pairs(mix_pooled_d5_NSW)

pairs(mix_basic_d5_AWN)
pairs(mix_hn_d5_AWN)
pairs(mix_pooled_d5_AWN)

pairs(mix_basic_d8_NSW)
pairs(mix_hn_d8_NSW)
pairs(mix_pooled_d8_NSW)

pairs(mix_basic_d8_AWN)
pairs(mix_hn_d8_AWN)
pairs(mix_pooled_d8_AWN)

a1_d5_basic_NSW<-anova(mod_probe_d5_basic_NSW)
a1_d5_hn_NSW<-anova(mod_probe_d5_hn_NSW)
a1_d5_pooled_NSW<-anova(mod_probe_d5_pooled_NSW)

a1_d5_basic_AWN<-anova(mod_probe_d5_basic_AWN)
a1_d5_hn_AWN<-anova(mod_probe_d5_hn_AWN)
a1_d5_pooled_AWN<-anova(mod_probe_d5_pooled_AWN)

a1_d8_basic_NSW<-anova(mod_probe_d8_basic_NSW)
a1_d8_hn_NSW<-anova(mod_probe_d8_hn_NSW)
a1_d8_pooled_NSW<-anova(mod_probe_d8_pooled_NSW)

a1_d8_basic_AWN<-anova(mod_probe_d8_basic_AWN)
a1_d8_hn_AWN<-anova(mod_probe_d8_hn_AWN)
a1_d8_pooled_AWN<-anova(mod_probe_d8_pooled_AWN)

a1_d5_basic_NSW
a1_d5_hn_NSW
a1_d5_pooled_NSW

a1_d5_basic_AWN
a1_d5_hn_AWN
a1_d5_pooled_AWN

a1_d8_basic_NSW
a1_d8_hn_NSW
a1_d8_pooled_NSW

a1_d8_basic_AWN
a1_d8_hn_AWN
a1_d8_pooled_AWN
```
